apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugins
  annotations:
    github.com/project-slug: kaulei-inc/backstage-community-plugins
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: other
  lifecycle: unknown
  owner: Infrastructure
