site_name: 'backstage-community-plugins'
nav:
  - Updating Yarn: https://github.com/kaulei-inc/backstage-community-plugins/blob/main/docs/updating-yarn.md
  - Version Bump: https://github.com/kaulei-inc/backstage-community-plugins/blob/main/docs/version-bump.md
  
plugins:
  - techdocs-core
