apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-plugins-doc
  links:
    - title: Website
      url: http://backstage.io
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: unknown
  owner: Infrastructure
